# Generated by Django 4.2.3 on 2023-11-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_placetovisit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceToVisit',
            new_name='Places',
        ),
    ]
