# Generated by Django 4.2.3 on 2023-11-04 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_placetovisit_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('itinerary', models.TextField(default='{}')),
            ],
        ),
        migrations.AlterField(
            model_name='places',
            name='city',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='places_to_visit/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cities')),
            ],
        ),
    ]
