<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-11-04 13:44
=======
# Generated by Django 3.2.4 on 2023-11-04 13:50
>>>>>>> 9368197c849da53471c97e8dfba537e91c1eaa32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cart_alter_places_city_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='places_to_visit/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cities')),
            ],
        ),
    ]
