# Generated by Django 4.2.3 on 2023-11-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='image',
            field=models.ImageField(upload_to='cuisine/'),
        ),
        migrations.AlterField(
            model_name='unique',
            name='city',
            field=models.TextField(),
        ),
    ]
