# Generated by Django 4.2.3 on 2023-11-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitySlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
