# Generated by Django 3.2.4 on 2023-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cityslang'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
