# Generated by Django 4.2.3 on 2023-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trip_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesListByActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('activity', models.TextField()),
                ('place_name', models.TextField()),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('contact', models.TextField()),
            ],
        ),
    ]
