# Generated by Django 3.2.4 on 2023-11-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_placeslistbyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='image',
            field=models.ImageField(default='hello', upload_to='cities/'),
            preserve_default=False,
        ),
    ]
